development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: erepair_development
  pool: 5
  username: root
  password: hugodpn
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: erepair_test
  pool: 5
  username: root
  password: hugodpn
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: erepair_production
  pool: 5
  username: root
  password: hugodpn
  socket: /var/run/mysqld/mysqld.sock
